package com.xworkz.runner;

import com.xworkz.hospitalDTO.HospitalDTO;
import com.xworkz.service.HospitalService;
import com.xworkz.service.HospitalServiceImp;

public class HospitalRunner {

	public static void main(String[] args) {
		
		HospitalDTO hospitalDTO1 = new HospitalDTO(1, "Jay Deva", "Cardiac", "CN Manjunath", 1970);
		HospitalDTO hospitalDTO2 = new HospitalDTO(2, "Arun", "Narayana", "General", 1980);
		HospitalDTO hospitalDTO3 = new HospitalDTO(3, "Jay", "Manju", "Cardiac", 1985);
		HospitalDTO hospitalDTO4 = new HospitalDTO(4, "kumar", "kumar", "Urology", 1968);
		HospitalDTO hospitalDTO5 = new HospitalDTO(5, "Ramakrishnan", "Ram", "Cardiac", 1990);
		HospitalDTO hospitalDTO6 = new HospitalDTO(6, "Ravi", "Vijayanand", "General", 1986);
		HospitalDTO hospitalDTO7 = new HospitalDTO(7, "CardiacSpeciality", "Vinay", "Heart", 1985);
		HospitalDTO hospitalDTO8 = new HospitalDTO(8, "Sachin", "Vishwa", "Lever", 1987);
		HospitalDTO hospitalDTO9 = new HospitalDTO(9, "lungPoint", "Ravindranath", "Lungs", 1996);
		HospitalDTO hospitalDTO10 = new HospitalDTO(10, "Swathi", "Swathi Krishnamurthi", "General", 2000);
		HospitalDTO hospitalDTO11 = new HospitalDTO(11, "Sudarshan", "Sudarshan", "Kidney", 2001);
		HospitalDTO hospitalDTO12 = new HospitalDTO(12, "Sundar", "Venkatesh", "Body", 2016);
		HospitalDTO hospitalDTO13 = new HospitalDTO(13, "Sindhu", "Prajwal", "Cardiac", 2008);
		HospitalDTO hospitalDTO14 = new HospitalDTO(14, " M V", "Veerabhadrappa", "Skin", 1998);
		HospitalDTO hospitalDTO15 = new HospitalDTO(15, "Danamma", "Ranganna", "Bone", 1997);
		HospitalDTO hospitalDTO16 = new HospitalDTO(16, "Devi", "Radhika", "Cardiac", 1999);
		HospitalDTO hospitalDTO17 = new HospitalDTO(17, "Manjunatha", "Manjanna", "General", 2000);
		HospitalDTO hospitalDTO18 = new HospitalDTO(18, "Dharma", "Chetan", "Heart", 1987);
		HospitalDTO hospitalDTO19 = new HospitalDTO(19, "Nava Ratna", "Chandranna", "Surgery", 1983);
		HospitalDTO hospitalDTO20 = new HospitalDTO(20, "Raghava", "Rajanna", "Eye", 1984);
		HospitalDTO hospitalDTO21 = new HospitalDTO(21, "Ram", "Siddappa", "Nose", 1988);
		HospitalDTO hospitalDTO22 = new HospitalDTO(22, "Ranga", "Manjappa", "Ear", 1999);
		HospitalDTO hospitalDTO23 = new HospitalDTO(23, "Sai", "Omkarappa", "Mouth", 1969);
		HospitalDTO hospitalDTO24 = new HospitalDTO(24, "Al-Ameen", "Surappa", "Brain", 1998);
		HospitalDTO hospitalDTO25 = new HospitalDTO(25, "Bapuji", "Suresh", "Heart", 1962);
		HospitalDTO hospitalDTO26 = new HospitalDTO(26, "Chirag", "Yogesh", "General", 1996);
		HospitalDTO hospitalDTO27 = new HospitalDTO(27, "City Central", "Hanumanth", "Cardiac", 1995);
		HospitalDTO hospitalDTO28 = new HospitalDTO(28, "Davanagere Heart", "Suhas", "Lungs", 1988);
		HospitalDTO hospitalDTO29 = new HospitalDTO(29, "Guru Poly Clinic", "Sachin", "Cancer", 1972);
		HospitalDTO hospitalDTO30 = new HospitalDTO(30, "MS Dental", "Basavarajappa", "Cardiac", 2006);
		HospitalDTO hospitalDTO31 = new HospitalDTO(31, "Nadigar Dental", "Naresh", "Heartr", 2008);
		HospitalDTO hospitalDTO32 = new HospitalDTO(32, "Narayana Hrudayalaya", "Nagesh", "Cardiac", 2010);
		HospitalDTO hospitalDTO33 = new HospitalDTO(33, "Nayana Eye", "Nagappa", "General", 2018);
		HospitalDTO hospitalDTO34 = new HospitalDTO(34, "New Dental", "Kallesh", "Urology", 1990);
		HospitalDTO hospitalDTO35 = new HospitalDTO(35, "Sai Multi Speciality", "Bojanna", "Brain", 2012);
		HospitalDTO hospitalDTO36 = new HospitalDTO(36, "Sreedurga", "Vasu", "Cardiac", 1972);
		HospitalDTO hospitalDTO37 = new HospitalDTO(37, "SS Hospital", "Darshan", "Body", 2014);
		HospitalDTO hospitalDTO38 = new HospitalDTO(38, "Suchetana", "Palakshappa", "Physiotherapy", 2016);
		HospitalDTO hospitalDTO39 = new HospitalDTO(39, "Spandana Urology", "Krishnamurti", "Polyclinic", 2015);
		HospitalDTO hospitalDTO40 = new HospitalDTO(40, "Surbhi", "Suresh", "Cardiac", 2019);
		HospitalDTO hospitalDTO41 = new HospitalDTO(41, "Veeresh ENT", "Ragini", "Cardiac", 1998);
		HospitalDTO hospitalDTO42 = new HospitalDTO(42, "Sri Nivasa", "Sumadura", "Plastic surgery", 1993);
		HospitalDTO hospitalDTO43 = new HospitalDTO(43, "Thrombosis", "Divyakka", "Cardiac", 2000);
		HospitalDTO hospitalDTO44 = new HospitalDTO(44, "Ullal Gen", "Vidyakka", "Heart", 2002);
		HospitalDTO hospitalDTO45 = new HospitalDTO(45, "Uma Nursing", "Sushmakka", "Cancer", 2005);
		HospitalDTO hospitalDTO46 = new HospitalDTO(46, "1 Health Medical", "Malatesh", "Cardiac", 1994);
		HospitalDTO hospitalDTO47 = new HospitalDTO(47, "32 Smiles", "Manoj", "Cardiac", 1993);
		HospitalDTO hospitalDTO48 = new HospitalDTO(48, "A Dent care", "Nanu", "Hair", 2000);
		HospitalDTO hospitalDTO49 = new HospitalDTO(49, "A J Dental", "Byrappa", "Cardiac", 2006);
		HospitalDTO hospitalDTO50 = new HospitalDTO(50, "A R clinic", "Barappa", "ENT", 2006);
		HospitalDTO hospitalDTO51 = new HospitalDTO(51, "Sumohan Medico", "Sanjanna", "Cardiac", 2009);
		HospitalDTO hospitalDTO52 = new HospitalDTO(52, "Sundar", "Ramappa", "Dental", 2016);
		HospitalDTO hospitalDTO53 = new HospitalDTO(53, "Supra", "Manikanta", "Cardiac", 2020);
		HospitalDTO hospitalDTO54 = new HospitalDTO(54, "Surabhi", "Sunil", "Emergency", 2019);
		HospitalDTO hospitalDTO55 = new HospitalDTO(55, "Suraksha", "Usha", "Cancer", 2017);
		HospitalDTO hospitalDTO56 = new HospitalDTO(56, "Surya", "Inchara", "Cardiac", 1989);
		HospitalDTO hospitalDTO57 = new HospitalDTO(57, "Sushruta", "Ravi", "Kidney", 1987);
		HospitalDTO hospitalDTO58 = new HospitalDTO(58, "Sushruta eye", "Chandru", "Eye", 1986);
		HospitalDTO hospitalDTO59 = new HospitalDTO(59, "Swathi ENT", "Chethan", "Cardiac", 1982);
		HospitalDTO hospitalDTO60 = new HospitalDTO(60, "Susruta", "Anil", "Cardiac", 1983);
		HospitalDTO hospitalDTO61 = new HospitalDTO(61, "Taluk Health", "Kempanna", "Cardiac", 1976);
		HospitalDTO hospitalDTO62 = new HospitalDTO(62, "Tanmay", "Charan", "Cardiac", 1979);
		HospitalDTO hospitalDTO63 = new HospitalDTO(63, "Tara", "Kuberappa", "Cardiac", 1985);
		HospitalDTO hospitalDTO64 = new HospitalDTO(64, "Telsang Maternity", "Chandan", "Cardiac", 1987);
		HospitalDTO hospitalDTO65 = new HospitalDTO(65, "The karnatak Cancer", "Sanjay", "Cardiac", 1998);
		HospitalDTO hospitalDTO66 = new HospitalDTO(66, "Thibbadevi", "Nityanand", "Cardiac", 1991);
		
		
		
		
		HospitalService hospitalService = new HospitalServiceImp();
		hospitalService.vaildateAndSave(hospitalDTO1);
		hospitalService.vaildateAndSave(hospitalDTO2);
		hospitalService.vaildateAndSave(hospitalDTO3);
		hospitalService.vaildateAndSave(hospitalDTO4);
		hospitalService.vaildateAndSave(hospitalDTO5);
		hospitalService.vaildateAndSave(hospitalDTO6);
		hospitalService.vaildateAndSave(hospitalDTO7);
		hospitalService.vaildateAndSave(hospitalDTO8);
		hospitalService.vaildateAndSave(hospitalDTO9);
		hospitalService.vaildateAndSave(hospitalDTO10);
		hospitalService.vaildateAndSave(hospitalDTO11);
		hospitalService.vaildateAndSave(hospitalDTO12);
		hospitalService.vaildateAndSave(hospitalDTO13);
		hospitalService.vaildateAndSave(hospitalDTO14);
		hospitalService.vaildateAndSave(hospitalDTO15);
		hospitalService.vaildateAndSave(hospitalDTO16);
		hospitalService.vaildateAndSave(hospitalDTO17);
		hospitalService.vaildateAndSave(hospitalDTO18);
		hospitalService.vaildateAndSave(hospitalDTO19);
		hospitalService.vaildateAndSave(hospitalDTO20);
		hospitalService.vaildateAndSave(hospitalDTO21);
		hospitalService.vaildateAndSave(hospitalDTO22);
		hospitalService.vaildateAndSave(hospitalDTO23);
		hospitalService.vaildateAndSave(hospitalDTO24);
		hospitalService.vaildateAndSave(hospitalDTO25);
		hospitalService.vaildateAndSave(hospitalDTO26);
		hospitalService.vaildateAndSave(hospitalDTO27);
		hospitalService.vaildateAndSave(hospitalDTO28);
		hospitalService.vaildateAndSave(hospitalDTO29);
		hospitalService.vaildateAndSave(hospitalDTO30);
		hospitalService.vaildateAndSave(hospitalDTO31);
		hospitalService.vaildateAndSave(hospitalDTO32);
		hospitalService.vaildateAndSave(hospitalDTO33);
		hospitalService.vaildateAndSave(hospitalDTO34);
		hospitalService.vaildateAndSave(hospitalDTO35);
		hospitalService.vaildateAndSave(hospitalDTO36);
		hospitalService.vaildateAndSave(hospitalDTO37);
		hospitalService.vaildateAndSave(hospitalDTO38);
		hospitalService.vaildateAndSave(hospitalDTO39);
		hospitalService.vaildateAndSave(hospitalDTO40);
		hospitalService.vaildateAndSave(hospitalDTO41);
		hospitalService.vaildateAndSave(hospitalDTO42);
		hospitalService.vaildateAndSave(hospitalDTO43);
		hospitalService.vaildateAndSave(hospitalDTO44);
		hospitalService.vaildateAndSave(hospitalDTO45);
		hospitalService.vaildateAndSave(hospitalDTO46);
		hospitalService.vaildateAndSave(hospitalDTO47);
		hospitalService.vaildateAndSave(hospitalDTO48);
		hospitalService.vaildateAndSave(hospitalDTO49);
		hospitalService.vaildateAndSave(hospitalDTO50);
		hospitalService.vaildateAndSave(hospitalDTO51);
		hospitalService.vaildateAndSave(hospitalDTO52);
		hospitalService.vaildateAndSave(hospitalDTO53);
		hospitalService.vaildateAndSave(hospitalDTO54);
		hospitalService.vaildateAndSave(hospitalDTO55);
		hospitalService.vaildateAndSave(hospitalDTO56);
		hospitalService.vaildateAndSave(hospitalDTO57);
		hospitalService.vaildateAndSave(hospitalDTO58);
		hospitalService.vaildateAndSave(hospitalDTO59);
		hospitalService.vaildateAndSave(hospitalDTO60);
		hospitalService.vaildateAndSave(hospitalDTO61);
		hospitalService.vaildateAndSave(hospitalDTO62);
		hospitalService.vaildateAndSave(hospitalDTO63);
		hospitalService.vaildateAndSave(hospitalDTO64);
		hospitalService.vaildateAndSave(hospitalDTO65);
		hospitalService.vaildateAndSave(hospitalDTO66);

	}

}
